# Sync Magnix env from Lifestyle_SuperApp (local only; .env is gitignored)
# Usage: .\scripts\sync-env-from-lifestyle.ps1 [-LifestyleRoot "C:\Users\nguye\Lifestyle_SuperApp"]

param(
  [string]$LifestyleRoot = (Join-Path $env:USERPROFILE "Lifestyle_SuperApp"),
  [string]$MagnixRoot = (Split-Path $PSScriptRoot -Parent)
)

$ErrorActionPreference = "Stop"

function Read-DotEnv([string]$Path) {
  $map = @{}
  if (-not (Test-Path $Path)) { return $map }
  Get-Content $Path -Encoding UTF8 | ForEach-Object {
    $line = $_.Trim()
    if (-not $line -or $line.StartsWith("#")) { return }
    if ($line -match '^([^=]+)=(.*)$') {
      $map[$matches[1].Trim()] = $matches[2].Trim()
    }
  }
  return $map
}

function Get-EnvVal($map, [string[]]$Keys) {
  foreach ($k in $Keys) {
    if ($map.ContainsKey($k) -and $map[$k]) { return $map[$k] }
  }
  return ""
}

$bdsEnvPath = Join-Path $LifestyleRoot "tools\workflow-bds-pipeline\.env"
$infraProdPath = Join-Path $LifestyleRoot "infrastructure\.env.production"

$bds = Read-DotEnv $bdsEnvPath
$infra = Read-DotEnv $infraProdPath
$all = @{}
foreach ($src in @($bds, $infra)) {
  foreach ($k in $src.Keys) { if ($src[$k]) { $all[$k] = $src[$k] } }
}

$outDir = Join-Path $MagnixRoot "n8n-workflows"
$credDir = Join-Path $outDir "credentials"
$outPath = Join-Path $outDir ".env"
$saSrc = Join-Path $LifestyleRoot "tools\workflow-bds-pipeline\service-account.json"
$saDst = Join-Path $credDir "google-service-account.json"

New-Item -ItemType Directory -Force -Path $credDir | Out-Null

if (Test-Path $saSrc) {
  Copy-Item -Force $saSrc $saDst
  Write-Host "Copied service account -> $saDst"
} else {
  Write-Warning "Missing $saSrc - skip Google SA copy"
}

$kodoRoot = Get-EnvVal $all @("KODO_DRIVE_ROOT_ID")
if (-not $kodoRoot) { $kodoRoot = "1gQcl4TBgm_LM5WvQDAoaLvnXUw2xQeX1" }

$n8nUrl = Get-EnvVal $all @("N8N_PUBLIC_URL")
if (-not $n8nUrl) { $n8nUrl = "https://n8n.vmd.asia" }

$lines = @(
  "# Auto-generated by sync-env-from-lifestyle.ps1 - DO NOT COMMIT",
  "# Sources: $bdsEnvPath, $infraProdPath",
  "",
  "MAGNIX_STORAGE_MODE=google_sheet_primary_drive_archive",
  "MAGNIX_WEBHOOK_TOKEN=",
  "MAGNIX_DRIVE_BACKUP=true",
  "",
  "# Google Sheet store of record + ops queues - fill manually",
  "GOOGLE_SHEET_DATABASE_ID=",
  "GOOGLE_SHEET_UID_TAB=uid_leads",
  "GOOGLE_SHEET_CONTENT_QUEUE_TAB=content_queue",
  "GOOGLE_SHEET_CONTENT_DRAFTS_TAB=content_drafts",
  "GOOGLE_SHEET_VIDEO_DRAFTS_TAB=video_drafts",
  "GOOGLE_SHEET_OUTREACH_TAB=outreach_queue",
  "GOOGLE_SHEET_CONTENT_METRICS_TAB=content_metrics",
  "GOOGLE_SHEET_CONTENT_SCORECARD_TAB=content_scorecard",
  "GOOGLE_SHEET_NOTIFICATION_EVENTS_TAB=notification_events",
  "",
  "# DeepSeek - fill manually (not in Lifestyle)",
  "DEEPSEEK_API_KEY=",
  "DEEPSEEK_API_URL=https://api.deepseek.com/chat/completions",
  "DEEPSEEK_MODEL=deepseek-chat",
  "",
  "# Google Drive archive - create Magnix_Automation folder and set ID",
  "GOOGLE_DRIVE_ARCHIVE_FOLDER_ID=",
  "GOOGLE_SERVICE_ACCOUNT_JSON=$saDst",
  "# KODO root reference from Lifestyle:",
  "# KODO_DRIVE_ROOT_ID=$kodoRoot",
  "",
  "# n8n VPS",
  "N8N_PUBLIC_URL=$n8nUrl"
)

Set-Content -Path $outPath -Value ($lines -join "`n") -Encoding UTF8
Write-Host "Wrote $outPath"

if (-not (Get-EnvVal $all @("GOOGLE_DRIVE_ARCHIVE_FOLDER_ID", "GOOGLE_DRIVE_FOLDER_ID"))) {
  Write-Warning "GOOGLE_DRIVE_ARCHIVE_FOLDER_ID empty - create Magnix_Automation archive folder on Drive"
}

Write-Host "Done. Import uid-ingest.workflow.json on $n8nUrl and set container env from .env"
